### ISSUE TITLE
Ошибка неверный путь

### ISSUE THREAD

**Issue by D10n1x** [azernov/gitmodx#3]
При установке по инструкции на чистый Modx возникла проблема дублирования части пути вот на таких участках
```php
$searchPathRel = $this->modx->getOption('site_elements_path','',MODX_CORE_PATH.'components/gitmodx/elements/');
        $searchPath = MODX_BASE_PATH.$searchPathRel;
```
У меня Modx в константу MODX_CORE_PATH в файле config.core.php записал полный путь от корня сервера до папки "core"(включая её) . И я так понял что константа MODX_BASE_PATH тоже содержала полный путь от корня сервера до корня сайта из-за чего возникала ошибка и скрипт не мог найти нужный путь и падал

**Comment by azernov** [comment]
Спасибо за комментарий. Не так давно делал правку, потом понял, что она некорректно отрабатывает. Сделал коммит, ошибка должна пропасть.
