### ISSUE TITLE
Выполнять trim() для имен элементов

### ISSUE THREAD

**Issue by shooter0106** [azernov/gitmodx#5]
Добрый день!

Сейчас столкнулся с тем что скопированый из БД элемент не может быть отрендерен. Дело в том что в конец имени файла попал пробел, видимо где-то внутри ядра MODX перед вызовом/сохранением элемента делается trim(). Может стоит тоже делать trim() в скрипте миграции?

Спасибо!

**Comment by azernov** [comment]
Сделал пару коммитов, в том числе, в них учел trim названий чанков/сниппетов/шаблонов
