### ISSUE TITLE
Абсолютные пути в статичных шаблонах

### ISSUE THREAD

**Issue by bxchkov** [azernov/gitmodx#7]
Из-за последнего слэша в конце пути MODX_BASE_PATH он не заменяется на пустую строку в пути к файлу шаблона. Предлагаю такое решение 
$fileRelative = str_replace(str_replace('\\','/',MODX_BASE_PATH),'',str_replace('\\','/',$file));
на 26 строке в loadtempates.php

**Comment by azernov** [comment]
Я так понимаю, что суть вашего решения состоит в том, чтобы предусмотреть вариант, когда в пути к файлу стоят обратные слеши, вместо прямых? На Unix-подобных системах путь разделяется прямыми слешами ( / ). Вы запускаете на windows и у вас в $file или MODX_BASE_PATH присутствуют обратные слеши ( \ )?

**Comment by azernov** [comment]
> Из-за последнего слэша в конце пути MODX_BASE_PATH он не заменяется на пустую строку в пути к файлу шаблона. Предлагаю такое решение $fileRelative = str_replace(str_replace('\','/',MODX_BASE_PATH),'',str_replace('\','/',$file)); на 26 строке в loadtempates.php

Я так понимаю, что суть вашего решения состоит в том, чтобы предусмотреть вариант, когда в пути к файлу стоят обратные слеши, вместо прямых? На Unix-подобных системах путь разделяется прямыми слешами ( / ). Вы запускаете на windows и у вас в $file или MODX_BASE_PATH присутствуют обратные слеши ( \ )?

**Comment by bxchkov** [comment]
Да, всё верно. Компонент подразумевает, что разработка будет вестись локально и разработчики на windows не защищены от подобных курьёзов)
